/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dependency;


public class Library implements Runnable{
    public boolean someLibraryMethod() {
        return true;
    }

    public static void info(){
        System.out.println("This is a library file");
    }

    @Override
    public void run() {
        info();
    }
}
