/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import dependency.RiskyServiceImpl;
import org.junit.jupiter.api.Test;
import java.io.IOException;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class AppTest {

    App app = new App(new RiskyServiceImpl());

    @Test
    void getSecretKey() throws IOException {
        String secretKey = app.getSecretKey();
        assertNotNull(secretKey);
    }

    @Test
    void kaaboom() {
        app.kaaboom();
        assertTrue(true); // are we still there
    }
}
