/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.viacom;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.AccessController;
import java.security.PrivilegedAction;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.setSecurityManager(new SecurityManager());

        String key = AccessController.doPrivileged(new PrivilegedAction<String>() {
            @Override
            public String run() {
                String path = System.getenv("KEYFILE_LOCATION");
                byte[] bytes = new byte[0];
                try {
                    bytes = Files.readAllBytes(Paths.get(path));
                } catch (IOException e) {
                    e.printStackTrace();
                }
                return new String(bytes);
            }
        });

        System.out.println(new App().getGreeting());
    }
}
